version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - temp_storage:/usr/src/app/temp

volumes:
  temp_storage:
