
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FileText, Eye } from "lucide-react";

interface DocumentPreviewProps {
  templateName: string;
  placeholderData: Record<string, string>;
  placeholders: string[];
}

const DocumentPreview = ({ templateName, placeholderData, placeholders }: DocumentPreviewProps) => {
  // Create a document-like preview by replacing placeholders with actual data
  const createDocumentPreview = () => {
    let content = `Dear [Recipient],

This is a sample document preview for ${templateName}.

`;

    placeholders.forEach((placeholder) => {
      const value = placeholderData[placeholder] || `[${placeholder}]`;
      content += `${placeholder.replace(/[_-]/g, ' ').toUpperCase()}: ${value}\n\n`;
    });

    content += `

Best regards,
[Your Name]

---
Generated by DocCraft
`;

    return content;
  };

  return (
    <Card className="h-full border-0 shadow-lg bg-white">
      <CardHeader className="pb-4">
        <CardTitle className="flex items-center space-x-2 text-lg">
          <Eye className="h-5 w-5 text-blue-600" />
          <span>Live Preview</span>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="bg-white border border-gray-200 rounded-lg shadow-sm">
          <div className="flex items-center space-x-2 mb-4 p-4 border-b bg-gray-50">
            <FileText className="h-5 w-5 text-gray-600" />
            <span className="font-medium text-gray-800">{templateName}</span>
          </div>
          
          <div className="p-6 max-h-96 overflow-y-auto">
            <div className="bg-white min-h-[400px] p-8 shadow-inner border border-gray-100 rounded-md" style={{
              fontFamily: 'Times, serif',
              lineHeight: '1.6',
              fontSize: '14px'
            }}>
              <div className="document-content">
                {placeholders.length > 0 ? (
                  <pre className="whitespace-pre-wrap text-gray-900 font-serif">
                    {createDocumentPreview()}
                  </pre>
                ) : (
                  <div className="text-center text-gray-500 py-16">
                    <FileText className="h-16 w-16 text-gray-300 mx-auto mb-4" />
                    <p className="text-lg">No content to preview</p>
                    <p className="text-sm">Upload a template with placeholders to see the preview</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
        
        <div className="text-xs text-gray-500 text-center">
          Document preview updates as you type
        </div>
      </CardContent>
    </Card>
  );
};

export default DocumentPreview;
