
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FileText, Eye } from "lucide-react";
import { useEffect, useRef } from "react";

interface RealDocumentPreviewProps {
  templateName: string;
  placeholderData: Record<string, string>;
  placeholders: string[];
}

const RealDocumentPreview = ({ templateName, placeholderData, placeholders }: RealDocumentPreviewProps) => {
  const previewRef = useRef<HTMLDivElement>(null);

  // Create a realistic document preview that mimics Word document styling
  const createRealisticDocument = () => {
    const content = `
      <div style="
        background: white;
        padding: 60px 80px;
        margin: 20px auto;
        box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        border-radius: 4px;
        max-width: 800px;
        min-height: 1000px;
        font-family: 'Times New Roman', serif;
        font-size: 12pt;
        line-height: 1.5;
        color: #000;
        position: relative;
      ">
        <!-- Document Header -->
        <div style="text-align: center; margin-bottom: 40px; border-bottom: 2px solid #333; padding-bottom: 20px;">
          <h1 style="font-size: 18pt; font-weight: bold; margin: 0; color: #1a365d;">
            ${templateName.replace('.docx', '').toUpperCase()}
          </h1>
          <p style="font-size: 10pt; color: #666; margin: 10px 0 0 0;">
            Generated Document - ${new Date().toLocaleDateString()}
          </p>
        </div>

        <!-- Document Body -->
        <div style="margin-bottom: 30px;">
          <p style="margin: 0 0 20px 0; text-align: justify;">
            Dear Recipient,
          </p>
          
          <p style="margin: 0 0 30px 0; text-align: justify;">
            This document has been generated using the template "${templateName}". 
            Please find below the information that has been filled in according to your requirements:
          </p>
        </div>

        <!-- Dynamic Fields Section -->
        <div style="margin: 30px 0;">
          ${placeholders.map(placeholder => {
            const value = placeholderData[placeholder] || `[${placeholder}]`;
            const isImage = value.startsWith('[Image:');
            const isEmpty = !placeholderData[placeholder] || placeholderData[placeholder].trim() === '';
            
            return `
              <div style="margin: 15px 0; padding: 10px; border-left: 3px solid #3182ce; background: ${isEmpty ? '#fff5f5' : '#f7fafc'};">
                <div style="display: flex; align-items: center; margin-bottom: 8px;">
                  <strong style="font-size: 11pt; color: #2d3748; text-transform: capitalize;">
                    ${placeholder.replace(/[_-]/g, ' ')}:
                  </strong>
                </div>
                <div style="margin-left: 20px; padding: 8px; background: white; border: 1px solid #e2e8f0; border-radius: 3px;">
                  ${isImage ? 
                    `<div style="color: #4a5568; font-style: italic; padding: 20px; text-align: center; background: #f7fafc; border: 1px dashed #cbd5e0;">
                       📷 ${value}
                       <br><small style="color: #718096;">Image will appear here in final document</small>
                     </div>` :
                    `<span style="color: ${isEmpty ? '#e53e3e' : '#2d3748'}; ${isEmpty ? 'font-style: italic;' : ''}">
                       ${isEmpty ? 'Not provided' : value}
                     </span>`
                  }
                </div>
              </div>
            `;
          }).join('')}
        </div>

        <!-- Document Footer -->
        <div style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #e2e8f0;">
          <p style="margin: 0 0 10px 0; text-align: justify;">
            Thank you for your attention to this matter. Should you require any clarification or additional information, 
            please do not hesitate to contact us.
          </p>
          
          <div style="margin-top: 40px;">
            <p style="margin: 0;">Best regards,</p>
            <div style="margin-top: 40px; border-bottom: 1px solid #333; width: 200px;"></div>
            <p style="margin: 10px 0 0 0; font-size: 10pt; color: #666;">Authorized Signature</p>
          </div>
        </div>

        <!-- Document Info Footer -->
        <div style="position: absolute; bottom: 20px; right: 20px; font-size: 8pt; color: #a0aec0;">
          Generated by DocCraft
        </div>
      </div>
    `;

    return content;
  };

  useEffect(() => {
    if (previewRef.current) {
      previewRef.current.innerHTML = createRealisticDocument();
    }
  }, [placeholderData, templateName, placeholders]);

  return (
    <Card className="h-full border-0 shadow-lg bg-white">
      <CardHeader className="pb-4">
        <CardTitle className="flex items-center space-x-2 text-lg">
          <Eye className="h-5 w-5 text-blue-600" />
          <span>Document Preview</span>
        </CardTitle>
      </CardHeader>
      <CardContent className="p-0">
        <div className="bg-gray-100 min-h-[600px] max-h-[800px] overflow-y-auto">
          {placeholders.length > 0 ? (
            <div ref={previewRef} className="p-4" />
          ) : (
            <div className="text-center text-gray-500 py-16 px-4">
              <FileText className="h-16 w-16 text-gray-300 mx-auto mb-4" />
              <p className="text-lg">No template content to preview</p>
              <p className="text-sm">Upload a template with placeholders to see the document preview</p>
            </div>
          )}
        </div>
        
        <div className="text-xs text-gray-500 text-center p-3 bg-gray-50">
          Live document preview • Updates as you type
        </div>
      </CardContent>
    </Card>
  );
};

export default RealDocumentPreview;
